spring.application.name=Project

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=movie_user
spring.datasource.password=parola
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

server.port=8080